### ISSUE TITLE
Freshen just errors out after fetching

### ISSUE THREAD

**Issue by neverfox** [LonoCloud/lein-voom#54]
```
Exception in thread "main" java.lang.AbstractMethodError: Method leiningen/voom/long_sha$nibbles.invokePrim(J)Ljava/lang/Object; is abstract
	at leiningen.voom.long_sha$nibbles.invokePrim(long_sha.clj)
	at leiningen.voom.long_sha.LongSha.toString(long_sha.clj:22)
	at clojure.core$str.invokeStatic(core.clj:542)
	at clojure.core$str.invoke(core.clj:533)
	at clojure.core$map$fn__4785.invoke(core.clj:2646)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:56)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$concat$cat__4448$fn__4449.invoke(core.clj:715)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$spread.invokeStatic(core.clj:626)
	at clojure.core$apply.invokeStatic(core.clj:641)
	at clojure.core$apply.doInvoke(core.clj:641)
	at clojure.lang.RestFn.invoke(RestFn.java:533)
	at leiningen.voom$exported_commits.invokeStatic(voom.clj:1032)
	at leiningen.voom$exported_commits.invoke(voom.clj:1022)
	at leiningen.voom$add_git_facts.invokeStatic(voom.clj:1164)
	at leiningen.voom$add_git_facts.invoke(voom.clj:1144)
	at leiningen.voom$updated_git_db.invokeStatic(voom.clj:1220)
	at leiningen.voom$updated_git_db.invoke(voom.clj:1215)
	at leiningen.voom$all_repo_dbs$iter__5410__5414$fn__5415$fn__5420.invoke(voom.clj:1237)
	at clojure.lang.Delay.deref(Delay.java:37)
	at clojure.core$deref.invokeStatic(core.clj:2228)
	at clojure.core$deref.invoke(core.clj:2214)
	at leiningen.voom$newest_voom_ver_by_spec$iter__5450__5462$fn__5463.invoke(voom.clj:1277)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$map$fn__4785.invoke(core.clj:2637)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
	at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__6738.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6545)
	at clojure.core$group_by.invokeStatic(core.clj:6860)
	at clojure.core$group_by.invoke(core.clj:6860)
	at leiningen.voom$fresh_version.invokeStatic(voom.clj:574)
	at leiningen.voom$fresh_version.invoke(voom.clj:566)
	at leiningen.voom$freshen$fn__5020.invoke(voom.clj:633)
	at clojure.core$map$fn__4785.invoke(core.clj:2646)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:688)
	at clojure.core$next__4341.invokeStatic(core.clj:64)
	at clojure.core$dorun.invokeStatic(core.clj:3033)
	at clojure.core$doall.invokeStatic(core.clj:3039)
	at clojure.core$doall.invoke(core.clj:3039)
	at leiningen.voom$freshen.invokeStatic(voom.clj:633)
	at leiningen.voom$freshen.doInvoke(voom.clj:606)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at leiningen.voom$voom.invokeStatic(voom.clj:1380)
	at leiningen.voom$voom.doInvoke(voom.clj:1368)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at leiningen.core.main$partial_task$fn__5829.doInvoke(main.clj:272)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at leiningen.core.main$apply_task.invokeStatic(main.clj:322)
	at leiningen.core.main$apply_task.invoke(main.clj:308)
	at leiningen.core.main$resolve_and_apply.invokeStatic(main.clj:328)
	at leiningen.core.main$resolve_and_apply.invoke(main.clj:324)
	at leiningen.core.main$_main$fn__5895.invoke(main.clj:401)
	at leiningen.core.main$_main.invokeStatic(main.clj:394)
	at leiningen.core.main$_main.doInvoke(main.clj:391)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.main$main_opt.invokeStatic(main.clj:314)
	at clojure.main$main_opt.invoke(main.clj:310)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at clojure.lang.Var.invoke(Var.java:394)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
```

**Comment by abrooks** [comment]
Sorry for the delay, @neverfox. This issue was triggered by the new direct linking changes in Clojure 1.8 and is fixed in our most recent release: 0.1.0-20160311_203101-g259fbfc
